linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - revive
    - gofmt
    - goimports
    - whitespace
    - typecheck

issues:
  exclude-use-default: false