run:
  go: '1.24'

linters-settings:
  goimports:
    local-prefixes: payment-processing-system

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - goimports
    - revive

issues:
  exclude-rules:
    # Exclude error checking in test files where it is often normal
    - path: _test\.go
      linters:
        - errcheck