# Dockerfile.migrator
FROM clickhouse/clickhouse-server:24.3

# Установи bash (в alpine он не установлен по умолчанию)
RUN apk add --no-cache bash

# Скопируй миграции
COPY migrations_clickhouse /migrations/

# Запусти скрипт
CMD ["bash", "-c", "
echo '🟡 Waiting for ClickHouse...'
while ! clickhouse-client --host clickhouse --port 9000 --query='SELECT 1' 2>/dev/null; do
  sleep 3
done
echo '✅ ClickHouse is ready. Applying migration...'

clickhouse-client --host clickhouse --port 9000 < /migrations/000001_create_fraud_reports.up.sql

echo '🎉 Migration completed.'
"]