# Role for general settings (users, security)
- name: Update apt cache and install required packages
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg', 'ufw']
    state: present
    update_cache: yes

- name: Create user
  user:
    name: '{{ ansible_user }}'
    shell: /bin/bash
    state: present
    create_home: yes

- name: Set up authorized key for user
  authorized_key:
    user: '{{ ansible_user }}'
    state: present
    key: "{{ lookup('file', (ssh_public_key_path | default(ansible_env.HOME ~ '/.ssh/id_rsa.pub'))) }}"

- name: Configure UFW firewall
  community.general.ufw:
    rule: allow
    port: '{{ item }}'
  loop: "{{ ([ufw_allowed_ports | default('22,80,443')]) | flatten | map('string') | join(',') | split(',') }}"
